name: sam3d-objects
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - attr=2.5.1=h166bdaf_1
  - binutils=2.43=h4852527_4
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - binutils_linux-64=2.43=h4852527_4
  - bzip2=1.0.8=h4bc722e_7
  - c-compiler=1.7.0=hd590300_1
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - cuda-cccl=12.1.109=ha770c72_0
  - cuda-cccl-impl=2.0.1=ha770c72_1
  - cuda-cccl_linux-64=12.1.109=ha770c72_0
  - cuda-command-line-tools=12.1.1=ha770c72_0
  - cuda-compiler=12.1.1=hbad6d8a_0
  - cuda-cudart=12.1.105=hd3aeb46_0
  - cuda-cudart-dev=12.1.105=hd3aeb46_0
  - cuda-cudart-dev_linux-64=12.1.105=h59595ed_0
  - cuda-cudart-static=12.1.105=hd3aeb46_0
  - cuda-cudart-static_linux-64=12.1.105=h59595ed_0
  - cuda-cudart_linux-64=12.1.105=h59595ed_0
  - cuda-cuobjdump=12.1.111=h59595ed_0
  - cuda-cupti=12.1.105=h59595ed_0
  - cuda-cupti-dev=12.1.105=h59595ed_0
  - cuda-cuxxfilt=12.1.105=h59595ed_0
  - cuda-driver-dev=12.1.105=hd3aeb46_0
  - cuda-driver-dev_linux-64=12.1.105=h59595ed_0
  - cuda-gdb=12.1.105=hd47b8d6_0
  - cuda-libraries=12.1.1=ha770c72_0
  - cuda-libraries-dev=12.1.1=ha770c72_0
  - cuda-nsight=12.1.105=ha770c72_0
  - cuda-nvcc=12.1.105=hcdd1206_1
  - cuda-nvcc-dev_linux-64=12.1.105=ha770c72_0
  - cuda-nvcc-impl=12.1.105=hd3aeb46_0
  - cuda-nvcc-tools=12.1.105=hd3aeb46_0
  - cuda-nvcc_linux-64=12.1.105=h8a487aa_1
  - cuda-nvdisasm=12.1.105=h59595ed_0
  - cuda-nvml-dev=12.1.105=h59595ed_0
  - cuda-nvprof=12.1.105=h59595ed_0
  - cuda-nvprune=12.1.105=h59595ed_0
  - cuda-nvrtc=12.1.105=hd3aeb46_0
  - cuda-nvrtc-dev=12.1.105=hd3aeb46_0
  - cuda-nvtx=12.1.105=h59595ed_0
  - cuda-nvvp=12.1.105=h59595ed_0
  - cuda-opencl=12.1.105=h59595ed_0
  - cuda-opencl-dev=12.1.105=h59595ed_0
  - cuda-profiler-api=12.1.105=ha770c72_0
  - cuda-sanitizer-api=12.1.105=h59595ed_0
  - cuda-toolkit=12.1.1=ha804496_0
  - cuda-tools=12.1.1=ha770c72_0
  - cuda-version=12.1=h1d6eff3_3
  - cuda-visual-tools=12.1.1=ha770c72_0
  - cxx-compiler=1.7.0=h00ab1b0_1
  - dbus=1.13.6=h5008d03_3
  - expat=2.6.4=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h48d6fc4_0
  - gcc=12.4.0=h236703b_2
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gcc_linux-64=12.4.0=h6b7512a_8
  - gds-tools=1.6.1.9=hd3aeb46_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - gxx=12.4.0=h236703b_2
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - gxx_linux-64=12.4.0=h8489865_8
  - harfbuzz=8.5.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libcap=2.75=h39aace5_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcublas=12.1.3.1=hd3aeb46_0
  - libcublas-dev=12.1.3.1=hd3aeb46_0
  - libcufft=11.0.2.54=hd3aeb46_0
  - libcufft-dev=11.0.2.54=hd3aeb46_0
  - libcufile=1.6.1.9=hd3aeb46_0
  - libcufile-dev=1.6.1.9=hd3aeb46_0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.2.106=hd3aeb46_0
  - libcurand-dev=10.3.2.106=hd3aeb46_0
  - libcusolver=11.4.5.107=hd3aeb46_0
  - libcusolver-dev=11.4.5.107=hd3aeb46_0
  - libcusparse=12.1.0.106=hd3aeb46_0
  - libcusparse-dev=12.1.0.106=hd3aeb46_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libglib=2.82.2=h2ff4ddf_1
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=hbd13f7d_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm19=19.1.2=ha7bfdaf_0
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnpp=12.1.0.40=hd3aeb46_0
  - libnpp-dev=12.1.0.40=hd3aeb46_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.18=h4ab18f5_2
  - libnvjitlink=12.1.105=hd3aeb46_0
  - libnvjitlink-dev=12.1.105=hd3aeb46_0
  - libnvjpeg=12.2.0.2=h59595ed_0
  - libnvjpeg-dev=12.2.0.2=ha770c72_0
  - libogg=1.3.5=h4ab18f5_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.47=h943b412_0
  - libpq=16.8=h87c4ccc_0
  - libsanitizer=12.4.0=ha732cd4_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxkbfile=1.1.0=h166bdaf_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h2d0b736_3
  - nsight-compute=2023.1.1.4=h3718151_0
  - nspr=4.36=h5888daf_0
  - nss=3.108=h159eef7_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pcre2=10.44=hba22ea6_2
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hb77b528_0
  - python=3.11.0=he550d4f_1_cpython
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astor==0.8.1
      - asttokens==3.0.1
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.1.0
      - auto-gptq==0.7.1
      - autoflake==2.3.1
      - av==12.0.0
      - azure-core==1.36.0
      - azure-identity==1.25.1
      - azure-storage-blob==12.27.1
      - azure-storage-file-datalake==12.22.0
      - babel==2.17.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.43.0
      - black==24.3.0
      - bleach==6.3.0
      - blinker==1.9.0
      - boto3==1.41.1
      - botocore==1.41.1
      - bpy==4.3.0
      - braceexpand==0.1.7
      - brotli==1.2.0
      - cachetools==6.2.2
      - calmsize==0.1.3
      - ccimport==0.4.4
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - circuitbreaker==2.1.3
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - conda-pack==0.7.1
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cramjam==2.11.0
      - crcmod==1.7
      - cryptography==45.0.7
      - cuda-python==12.1.0
      - cumm-cu121==0.7.11
      - cycler==0.12.1
      - cython==3.2.1
      - dash==3.3.0
      - dataclasses==0.6
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - deprecation==2.1.0
      - dill==0.4.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docopt==0.6.2
      - easydict==1.13
      - edt==3.1.0
      - einops==0.8.1
      - einops-exts==0.0.4
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - executing==2.2.1
      - fastapi==0.121.3
      - fastavro==1.9.4
      - fastcore==1.8.16
      - fasteners==0.19
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.20.0
      - findpydeps==0.2.8
      - fire==0.7.1
      - flake8==7.0.0
      - flash-attn==2.8.3
      - flask==3.0.3
      - fonttools==4.60.1
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.2.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gekko==1.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glcontext==3.0.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==2.10.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gradio==5.49.0
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - gsplat==1.5.3
      - h11==0.16.0
      - h5py==3.12.1
      - hdfs==2.7.3
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - humanize==4.14.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.11
      - igraph==0.11.8
      - imageio==2.37.2
      - imath==0.0.2
      - importlib-metadata==6.11.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipycanvas==0.14.1
      - ipyevents==2.0.4
      - ipykernel==6.29.5
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonlines==4.0.0
      - jsonpickle==3.0.4
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kagglehub==0.3.13
      - kaolin==0.17.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - libcst==1.8.6
      - librosa==0.10.1
      - lightning==2.3.3
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - loguru==0.7.2
      - lovely-numpy==0.2.18
      - lovely-tensors==0.1.20
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - medim==0.1.2
      - mistune==3.1.4
      - mock==4.0.3
      - moderngl==5.12.0
      - moge==1.0.0
      - monai==1.5.1
      - more-itertools==10.8.0
      - moreorless==0.5.0
      - mosaicml-streaming==0.7.5
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nibabel==5.3.2
      - nilearn==0.12.1
      - ninja==1.13.0
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - nvidia-pyindex==1.0.9
      - objsize==0.7.0
      - oci==2.164.0
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.12.0.88
      - openexr==3.3.3
      - optimum==1.18.1
      - optree==0.14.1
      - orjson==3.10.0
      - overrides==7.7.0
      - panda3d==1.10.15
      - panda3d-gltf==1.2.1
      - panda3d-simplepbr==0.13.1
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - parso==0.8.5
      - pathos==0.3.4
      - pathspec==0.12.1
      - pccm==0.4.16
      - pdoc3==0.10.0
      - peft==0.10.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==11.3.0
      - pip-system-certs==4.0
      - pipdeptree==2.28.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - pluggy==1.6.0
      - plyfile==1.1.3
      - point-cloud-utils==0.29.5
      - polyscope==2.3.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - pox==0.3.6
      - ppft==1.7.7
      - prefetch-generator==1.0.3
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycocotools==2.0.7
      - pycodestyle==2.11.1
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydot==1.4.2
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pyglet==2.1.11
      - pygltflib==1.16.5
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymeshfix==0.17.0
      - pymongo==4.6.3
      - pynacl==1.6.1
      - pynvml==13.0.1
      - pyopengl==3.1.0
      - pyopenssl==25.1.0
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pysocks==1.7.1
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - python-pycg==0.9.2
      - python-snappy==0.7.3
      - pytorch-lightning==2.5.6
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pyvista==0.46.4
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - randomname==0.2.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - roma==1.5.1
      - rootutils==1.0.7
      - rouge==1.0.1
      - rpds-py==0.29.0
      - rsa==4.9.1
      - rtree==1.3.0
      - ruff==0.14.6
      - s3transfer==0.15.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - sagemaker==2.242.0
      - sagemaker-core==1.0.68
      - sam-2==1.0
      - sam3d-objects==0.0.1
      - schema==0.7.8
      - scikit-image==0.23.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - scooby==0.11.0
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==2.6.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.45.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - simpleitk==2.5.3
      - simplejson==3.19.2
      - six==1.17.0
      - smdebug-rulesconfig==1.0.1
      - smmap==5.0.2
      - smplx==0.1.28
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - spconv-cu121==2.3.8
      - stack-data==0.6.3
      - starlette==0.50.0
      - stdlibs==2025.10.28
      - submitit==1.5.3
      - surface-distance==0.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.2.2
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==0.9.16
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.13.3
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchio==0.21.0
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - trailrunner==1.4.0
      - traitlets==5.14.3
      - trame==3.12.0
      - trame-client==3.11.2
      - trame-common==1.0.1
      - trame-server==3.8.1
      - transformers==4.57.1
      - trimesh==4.9.0
      - triton==3.1.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - usd-core==25.11
      - usort==1.0.8.post1
      - utils3d==0.0.2
      - uvicorn==0.38.0
      - vtk==9.5.2
      - wadler-lindig==0.1.7
      - wandb==0.20.0
      - warp-lang==1.10.0
      - wcwidth==0.2.14
      - webcolors==1.13
      - webdataset==0.2.86
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - wslink==2.5.0
      - xatlas==0.0.9
      - xformers==0.0.28.post3
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
      - zstd==1.5.7.2
prefix: /shared/ssd_28T/home/yl535/anaconda3/envs/sam3d-objects
